Missing functions addition
SFML/CSFML pull request #148
Opened 2019-11-22 21:13 UTC by Luhrel

sfTexture_bind: Added sfTextureCoordinateType arg

Added functions:
sfContext_isExtensionAvailable -> sf::Context::isExtensionAvailable static bool

sfTextureCoordinateType -> sf::Texture::CoordinateType enum

sfRenderWindow_drawVertexBufferWithIndex &
sfRenderTexture_drawVertexBufferWithIndex
-> sf::RenderTarget::draw(vertexBuffer, firstVertex, vertexCount)

2019-12-27 08:12 UTC, LaurentGomila commented
There's a reason why some of these functions are not implemented. They are either for internal use (when it's the case, they are clearly documented as such) or not needed in C because of the API differences.

Of course, some functions may also simply be missing, most likely those that were added recently 😉

2019-12-27 08:59 UTC, Luhrel commented
Yup I know and I didn't implemented those, did I ?
Which funcs (in this PR) aren't needed in C ?

2019-12-27 15:54 UTC, LaurentGomila commented
`sfTcpListener_close` is not needed since you just free (`sfTcpListener_destroy`) the instance when you're done with it.

`sfTextureCoordinateType` and where it's used, were initially meant for internal use only. I'm not sure if that changed since then.

2019-12-27 22:16 UTC, Luhrel commented
> `sfTcpListener_close` is not needed since you just free (`sfTcpListener_destroy`) the instance when you're done with it.

Ok, but should we add it anyway for the other SFML bindings ?

> `sfTextureCoordinateType` and where it's used, were initially meant for internal use only. I'm not sure if that changed since then.

The doc just says : 

> [...] [sf::CoordinateType::Pixels] is used internally by the graphics classes of SFML, it makes the definition of texture coordinates more intuitive for the high-level API, users don't need to compute normalized values.

So it may be used.

2019-12-28 06:46 UTC, LaurentGomila commented
> Ok, but should we add it anyway for the other SFML bindings (which are based on CSFML) ?

Nop.

2020-05-07 16:39 UTC, silverweed commented
@LaurentGomila how about the VertexBuffer functions? Would they be accepted if they were isolated in their own PR?

2020-05-07 16:49 UTC, LaurentGomila commented
Is `sf::VertexBuffer` part of the latest version, or does it have to be released yet (I really don't remember 😁)?

2020-05-07 17:21 UTC, silverweed commented
It's surely there in SFML 2.5 :D

2020-05-07 19:14 UTC, LaurentGomila commented
Then OK, it should be in CSFML and SFML.Net too.

2020-05-07 19:23 UTC, silverweed commented
Ok, cool :)
@Luhrel, would you rather split your PR or let me reopen mine (#153)?

2020-05-07 20:03 UTC, Luhrel commented
@silverweed There's no need to split/reopen. All the functions in this PR is for the 2.5.

@LaurentGomila Which name do you prefer `sfRenderTexture_drawVertexBufferWithIndex` or `sfRenderTexture_drawVertexBufferRange` ?

2020-05-08 06:41 UTC, LaurentGomila commented
I'd say `sfRenderTexture_drawVertexBufferRange`.

2020-05-08 09:25 UTC, Luhrel commented
@LaurentGomila Done. Maybe you can merge this now :wink:

2020-07-27 13:46 UTC, silverweed commented
@LaurentGomila any news on this?

2022-10-26 21:30 UTC, eXpl0it3r requested changes
Really sorry for the long wait on this 😓 

Can you squash the two vertex buffer commits and fix the small style changes?

2022-10-26 21:30 UTC, eXpl0it3r commented on include/SFML/Graphics/RenderTexture.h
> +                                                  size_t vertexCount, const sfRenderStates* states);
Align with opening parenthesis like the `drawPrimitives` below

2022-10-26 21:30 UTC, eXpl0it3r commented on include/SFML/Graphics/RenderWindow.h
> +                                                  size_t vertexCount, const sfRenderStates* states);
Align with opening parenthesis like the `drawPrimitives` below

2022-10-26 21:30 UTC, eXpl0it3r commented on src/SFML/Graphics/RenderTexture.cpp
> +                                              size_t vertexCount, const sfRenderStates* states)
Align with opening parenthesis like the `drawPrimitives` below

2022-10-27 18:24 UTC, eXpl0it3r approved these changes

2022-10-27 20:01 UTC, eXpl0it3r commented
Allowed myself to integrate the last commit in the relevant commits and rebase, as the pipeline was slightly outdated 😅

2022-10-27 20:11 UTC, merged

2022-10-27 20:12 UTC, eXpl0it3r commented
Thanks a lot for these fixes and the patience. 🥳 

Sorry again it took so long 😞