added functions for creating sRGB enabled textures from file / memory, etc.
SFML/CSFML pull request #177
Opened 2022-12-16 21:09 UTC by EnokViking

2022-12-19 22:44 UTC, eXpl0it3r requested changes
Just some documentation adjustments 🙂

2022-12-19 22:44 UTC, eXpl0it3r commented on include/SFML/Graphics/Texture.h
> +/// \brief Create a texture configured for srgb from a file
sRGB

2022-12-19 22:44 UTC, eXpl0it3r commented on include/SFML/Graphics/Texture.h
> +/// When providing texture data from an image file or memory, it can
I think there should be an empty comment line between brief and the extended text

2022-12-19 22:44 UTC, eXpl0it3r commented on include/SFML/Graphics/Texture.h
> +/// the texture data in order for the setting to take effect.
This doesn't make sense here, as we're already loading the texture

2022-12-19 22:44 UTC, eXpl0it3r commented on include/SFML/Graphics/Texture.h
> +/// \brief Create a new texture from a file in memory
Maybe squeeze `sRGB` somewhere in

2022-12-19 22:44 UTC, eXpl0it3r commented on include/SFML/Graphics/Texture.h
> +/// \brief Create a new texture from a custom stream
Maybe squeeze `sRGB` somewhere in

2022-12-19 22:44 UTC, eXpl0it3r commented on include/SFML/Graphics/Texture.h
> +/// \brief Create a new texture from an image
Maybe squeeze `sRGB` somewhere in

2022-12-23 11:14 UTC, Bambo-Borris approved these changes
Checked it out locally and compared C++ results to C ones and got the same end result.

2022-12-25 20:37 UTC, eXpl0it3r approved these changes

2022-12-25 21:47 UTC, merged

2022-12-25 22:05 UTC, eXpl0it3r commented
Thanks a ton for getting this fixed! 🙂