Pull request for 2.6.x CSFML
SFML/CSFML pull request #186
Opened 2023-05-17 00:47 UTC by dogunbound

This PR will be for getting all of the 2.6.x features into CSFML. Here is a test project that I have opensource to test the project with. Currently I have font enabling and disable by pressing the s key https://github.com/dogunbound/CSFML_2.6_sample 

I hope we can hack this out. 2.6.x is pretty stable at this point, so I think it would be good to begin working on this.

2023-05-17 06:39 UTC, eXpl0it3r commented
Need to update the ci.yml to use the 2.6.x branch (and later 2.6.0 tag) 

https://github.com/SFML/CSFML/blob/39d7c47f041ac0401e9dcd39638af2327f5982c5/.github/workflows/ci.yml#L28

2023-05-26 20:22 UTC, dogunbound commented
Someone Might want to test the packets getter function. I haven't got the slightest idea as to how I would test it.

2023-06-07 16:20 UTC, shane-tran-whitmire commented
@eXpl0it3r @ChrisThrasher 

I managed to hack through the entire list for all of the obvious ones that don't need updates on CSFML's end. The rest of the unchecked issues / PRs are ones that I wasn't sure needed changes to CSFML's end, or one's that need changes to CSFML's end. If you could help me go through the rest of this list, that would be grand.

2023-06-07 16:23 UTC, ChrisThrasher commented
To make sure I understand, you went through every PR after `2.5.1` and make checkboxes in this issue with indicating whether or not we have more work to do to implement a given PR in CSFML? _Wow_ that's an incredible effort and I really appreciate it. This will make it so much easier to know what all is remaining to do on CSFML 2.6.0.

2023-06-07 16:29 UTC, shane-tran-whitmire commented
> To make sure I understand, you went through every PR after `2.5.1` and make checkboxes in this issue with indicating whether or not we have more work to do to implement a given PR in CSFML? _Wow_ that's an incredible effort and I really appreciate it. This will make it so much easier to know what all is remaining to do on CSFML 2.6.0.

To be specific, I got the changelog.md change from this PR https://github.com/SFML/SFML/pull/2482/files?diff=unified&w=0 and parsed all of the numbers for matching pull requests.

2023-06-07 16:32 UTC, shane-tran-whitmire commented
@ChrisThrasher I should also add, there are already a couple of additions in this pull request. I have font smoothing disabling (a feature I REALLY want), and some networking this already committed.

2023-06-07 18:05 UTC, ChrisThrasher requested changes
Just a few simple formatting fixes to get started

2023-06-07 18:05 UTC, ChrisThrasher commented on include/SFML/Graphics/Font.h
> +
```suggestion
```

2023-06-07 18:05 UTC, ChrisThrasher commented on src/SFML/Graphics/Font.cpp
> +////////////////////////////////////////////////////////////
```suggestion

////////////////////////////////////////////////////////////
```

2023-06-07 18:05 UTC, ChrisThrasher commented on src/SFML/Graphics/Font.cpp
> +
```suggestion


```

2023-06-07 18:05 UTC, ChrisThrasher commented on src/SFML/Network/Packet.cpp
> +////////////////////////////////////////////////////////////
```suggestion

////////////////////////////////////////////////////////////
```

2023-06-23 06:45 UTC, eXpl0it3r commented
Re-triggered the job runs, now that the `2.6.0` tag actually exists.

2023-06-23 20:45 UTC, ChrisThrasher commented
Can we move this list into a separate issue that we can incrementally tackle these changes over multiple PRs? That will make it easier for multiple people to work concurrently if need be. We can still merge the progress already made in this PR.

2023-06-23 21:38 UTC, ChrisThrasher approved these changes

2023-06-23 21:50 UTC, ChrisThrasher commented
See #187 for this same list but in a separate issue. Please do not use this particular PR for more work progress tracking.

2023-06-25 17:40 UTC, dogunbound commented
Marked it as non-draft. You can merge it now.

2023-06-26 19:11 UTC, eXpl0it3r approved these changes

2023-06-26 19:20 UTC, merged

2023-06-26 19:20 UTC, eXpl0it3r commented
Thank you for getting this started! 🙂