Implement scancodes
SFML/CSFML pull request #197
Opened 2023-07-05 03:04 UTC by ChrisThrasher

Implements https://github.com/SFML/SFML/pull/1235

I expected this be harder but the scan code interface is actually very simple. It's the implementation in SFML where all the complexity lies.

2023-07-05 13:28 UTC, shane-tran-whitmire approved these changes
Wow, I expected scancodes to be much more complicated.

2023-07-05 17:49 UTC, kimci86 requested changes
This is missing changes to `sfEvent`.

2023-07-05 17:59 UTC, ChrisThrasher commented
> This is missing changes to `sfEvent`.

I made those changes last night and pushed them multiple times but I can't get this PR thread to update. [Here's proof.](https://github.com/SFML/CSFML/commit/15e26f9bc0313e2eda130b99b5461bee7a8e753b)

2023-07-06 22:02 UTC, ChrisThrasher commented
Looks like this PR thread finally updated with the changes I made

2023-07-07 06:23 UTC, eXpl0it3r approved these changes

2023-07-07 06:32 UTC, merged