Implement `sf::Vulkan` functions
SFML/CSFML pull request #198
Opened 2023-07-05 03:52 UTC by ChrisThrasher

Implements https://github.com/SFML/SFML/pull/1557

2023-07-05 13:22 UTC, shane-tran-whitmire approved these changes
This is my work account. You can consider this a regular approval

2023-07-06 19:48 UTC, kimci86 approved these changes

2023-07-06 21:13 UTC, eXpl0it3r requested changes

2023-07-06 21:13 UTC, eXpl0it3r commented on src/SFML/Window/Vulkan.cpp
> +    return sf::Vulkan::getGraphicsRequiredInstanceExtensions().data();
`data()` is a C++11 function 😅

2023-07-06 21:49 UTC, eXpl0it3r approved these changes

2023-07-06 21:57 UTC, merged