Use inheritance to remove `This` data member
SFML/CSFML pull request #347
Opened 2024-09-20 23:01 UTC by ChrisThrasher

Closes #222

It's reasonable to say that, for example, sfImage _is_ an sf::Image. This "is-a" relationship is what inheritance does a very good job modeling. By using inheritance to implement CSFML types in terms of their SFML counterpart, we get code that is simpler and easier to read. We also avoid some of the extra "dancing" required to construct a CSFML type from an SFML type. This improves the encapsulation of our CSFML implementation.

2024-09-21 21:06 UTC, ZXShady requested changes
remove unnecessary ternary and static cast

2024-09-22 04:11 UTC, ZXShady requested changes
readd assert and remove unnecessary static_cast and ternary

2024-09-22 04:11 UTC, ZXShady commented on src/CSFML/Graphics/Shader.cpp
> -    assert(name);
is there a reason for removing this assert? might have been accidental

2024-09-22 04:11 UTC, ZXShady commented on src/CSFML/Graphics/Shader.cpp
> +    sf::Shader::bind(shader ? static_cast<const sf::Shader*>(shader) : nullptr);
the static cast is unnecessary and the ternary is also unnecessary

the implicit Derived to Base conversion is enough.

2024-09-23 08:40 UTC, eXpl0it3r commented
Could this cause issues from pure C side or a binding using CSFML? We're only returning pointers and have typedefs, but now the fundamental type is no longer just a simple struct 🤔

2024-09-23 09:09 UTC, ZXShady commented
the type was never a simple struct to begin with the sf Classes had non standard layout types inside it. and the typedef is to make the pointer opaque.

2024-09-23 15:52 UTC, ChrisThrasher commented
> Could this cause issues from pure C side or a binding using CSFML? We're only returning pointers and have typedefs, but now the fundamental type is no longer just a simple struct 🤔

Notice how this PR only touches the `src/` directory. Users have no way to observe structs that are defined in `src/`. They can only see the definition of structs defined in `include/`. This is the reason we use opaque pointers in the interface. It gives us full freedom to implement these structs however we like.

2024-09-23 22:59 UTC, eXpl0it3r commented
I get that, I was just wondering if there's any limit to that. We now had opaque pointers to structs, but now it's a derived type. Can this have any side effect from a C/binding point of view?

2024-09-23 23:09 UTC, ChrisThrasher commented
No, there’s no way for users to notice anything has changed.

2024-09-24 16:57 UTC, ZXShady approved these changes

2024-09-24 17:05 UTC, merged