use aggregate initialization to initialize
SFML/CSFML pull request #358
Opened 2024-09-27 23:17 UTC by ZXShady

I personally think it is clearer than the variable + member assignments as the layout of sfColor is guranteed and known and this removes some intermediary variables.

2024-09-28 00:32 UTC, ChrisThrasher requested changes

2024-09-28 00:32 UTC, ChrisThrasher commented on src/CSFML/Graphics/Transform.cpp
> +        a20,a21,a22,
```suggestion
        a00, a01, a02,
        a10, a11, a12,
        a20, a21, a22,
```

2024-09-28 00:33 UTC, ChrisThrasher approved these changes

2024-09-28 00:42 UTC, merged

2024-11-01 08:19 UTC, kimci86 commented on src/CSFML/System/Time.cpp
> +    return {static_cast<int64_t>(amount * 1000)};
For the record, bug here got fixed in #360